### ISSUE TITLE
Doesn't work with Svelte (so most likely doesn't work with Vite in general?)

### ISSUE THREAD

**Issue by evangelos-ch** [knocklabs/javascript#20]
Hi!

I'm working on a hobby project written in SvelteKit hosted on Vercel, and I'm looking for a notification solution. After seeing Vercel's blogpost giving Knock a glowing recommendation I decided to try and integrate it into my app, however the client just does not seem to initialise. Might be a problem when running under Vite (the bundler Svelte uses)?

This is the code I have in a utility file:

```ts
import { PUBLIC_KNOCK_API_KEY } from '$env/static/public';
import Knock from '@knocklabs/client';

const client = new Knock(PUBLIC_KNOCK_API_KEY);

export default client;
```

And even just this fails to run with the following stack trace:
```
TypeError: Cannot read properties of undefined (reading 'default')
    at MY_PROJECT_SRC/knock/client.ts:4:19
    at async instantiateModule (file:///MY_PROJECT/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:52224:9)
TypeError: Cannot read properties of undefined (reading 'default')
    at MY_PROJECT_SRC/knock/client.ts:4:19
    at async instantiateModule (file:///MY_PROJECT/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:52224:9)
```

Obviously I stubbed out my actual file paths in the above error snippet for privacy reasons.

I was also getting a warning about needing `"type": "module"` in the `package.json` file for the Knock client, which I put in myself locally to see if it made any difference and it made the warning go away but it did not fix the problem, it still errors out and doesn't work.

Would be great if you could look into this! Though seeing how the client documentation is somewhat out of date with the actual API and a few months old stale issues in this repo I assume this client is not at the top of your priorities... Pity, as it looks like a great solution for my use case!

**Comment by kylemcd** [comment]
This should be fixed by #22

**Comment by patrikengborg** [comment]
I still have this problem in a SvelteKit app. It seems this fix: https://github.com/knocklabs/javascript/commit/59ce04400058e7d08925a20f925e80c1760e23e0 has been merged to @knocklabs/react but not to @knocklabs/client.

Can you please merge it to @knocklabs/client and see if that resolves it?

**Comment by kylemcd** [comment]
@patrikengborg Working through a fix now, will update you here when it's released.

**Comment by kylemcd** [comment]
@patrikengborg v0.1.9 is now available and should fix the issues that you are seeing: https://www.npmjs.com/package/@knocklabs/react/v/0.1.9

**Comment by patrikengborg** [comment]
It works! Great job, thanks a lot!
